/*
 * This header file defines the errorcodes for the error handling.
 */

#ifndef _REPORTERROR_H
#define _REPORTERROR_H

typedef enum
{
    SUCCESS = 0,
    INVALID_INPUT = -1,
    FILE_NOT_FOUND = -2,
    MEMORY_ALLOCATION_FAILED = -3,
    FAILED_TO_EXECUTE_GETTIMEOFDAY = -4,
    INVALID_COMMAND = -5,
    MEMORY_FREE_SUCCESS = -6,
    ATTEMPT_TO_FREE_UNALLOCATED_STORAGE = -7,
    PID_MISSMATCH = -8,
    INVALID_ADDRESS_IN_THE_MEMORY = -9,
    OUT_OF_MAIN_MEMORY = -10,
    NULL_POINTER_NO_EFFECT = -11,
    UNBLE_TO_CONFIGURE_UART = -12,
    DEVICE_NAME_NOT_FOUND = -13,
    FILE_NAME_NOT_FOUND = -14,
    NO_ASSIGNMENT = -15,
    MAX_OPEN_STREMS_LIMIT_REACHED = -16,
    NOTHING_MATCHED = -17,
    ONLY_BYTE_LEVEL_OPERATIONS = -18,
    DEVICE_ALREADY_OPEN = -19,
    FILE_ALREADY_OPEN = -20,
    DEFAULT_STREAMS_ALREADY_OPEN = -21,
    COPY_FAILURE = -22,
    INVALID_FILE_DISCRIPTOR = -23,
    EOF_REACHED = -24,
    INVALID_FOPEN_MODE = -25,
    FILE_NOT_OPEN_FOR_WRITE = -26,
    FILE_NOT_OPEN_FOR_READ = -27,
    DO_NOT_CLOSE_DEFAULT_STREAMS = -28,
    OUTPUT_ONLY_STREAMS = -29,
    INPUT_ONLY_STREAMS = -30,
    FGETS_ONLY_FOR_FILES = -31,
    OUPUT_ONLY_DEVICE = -32,
    INPUT_ONLY_DEVICE = -33,
    INVALID_CREDENTIALS = -34,
    USERNAME_MISSMATCH = -35,
    LOGIN_SUCCESSFULL = -36,
    TERMINATE = -37,
    EPOCH_COUNT_IS_NOT_SET = -38,
    FILE_ALREADY_EXISTS_WITH_SAME_NAME = -39,
    INVALID_MODE = -40,
    USER_MUST_SET_THE_EPOCH_CLOCK = -41,
    DID_YOU_MEANT_TO_PROVIDE_ISO8601_TIME = -42,
    CANNOT_ALLOCATE_SIZE_0_OR_NEGETIVE = -43,
    INVALID_MORSE_INPUT_CHAR = -44,
    UNPRIVILEGED_USER_ACTION = -45,
    UNABLE_TO_SPAWN_A_PROCESS = -46,
    MAX_ERRORCODE_INDEX = -47,    
} errorCode;

/* ERROR_CODE_MAX_INDEX = the errorcode with maximum enum absolute value */
#define ERROR_CODE_MAX_INDEX abs(MAX_ERRORCODE_INDEX)

void SVCreportErrorImpl(errorCode);

#endif /* ifndef _REPORTERROR_H */
